# Save in utils_export.R

#' Collect all SQL queries and R code needed to reproduce subst_pp_df
#' @param prescription_query Query object for prescriptions
#' @param ltc_query Query object for LTCs
#' @param patient_query Query object for patient data
#' @param outcome_query Query object for outcomes
#' @param file_path Path where to save the SQL file
#' @return None
export_sql_commands <- function(prescription_query, ltc_query, patient_query, outcome_query, file_path) {
	# Create header with timestamp and description
	header <- paste0("# R script to reproduce subst_pp_df\n",
									 "# Generated on: ", Sys.time(), "\n\n")

	# Add required libraries
	libraries <- c(
		"# Required libraries",
		"library(data.table)",
		"library(bit64)",
		"library(DBI)",
		"library(RPostgres)",
		"",
		"# Database connection parameters",
		"db_params <- list(",
		"  drv = Postgres(),",
		"  dbname = 'iphs_finer_cprd',",
		"  host = 'db1',",
		"  port = 5432,",
		"  user = 'iphs_finer_cprd',",
		"  password = 'ies4phahph3A'",
		")",
		"",
		"# Create database connection",
		"con <- do.call(dbConnect, db_params)",
		""
	)

	# Format queries with comments and parameters
	queries <- c(
		"# Execute queries",
		"",
		"# Patient data query",
		"patient_query <- list(",
		paste0("  query = '", patient_query$query, "',"),
		paste0("  params = list(", paste(sprintf("'%s'", unlist(patient_query$params)), collapse = ", "), ")"),
		")",
		"patient_data <- as.data.table(dbGetQuery(con, patient_query$query, params = unlist(patient_query$params)))",
		"patient_data[, dob := as.IDate(dob)]",
		"patient_data$patid <- bit64::as.integer64(patient_data$patid)",
		"setkey(patient_data, patid)",
		"",
		"# Prescription data query",
		"prescription_query <- list(",
		paste0("  query = '", prescription_query$query, "',"),
		paste0("  params = list(", paste(sprintf("'%s'", unlist(prescription_query$params)), collapse = ", "), ")"),
		")",
		"prescription_data <- as.data.table(dbGetQuery(con, prescription_query$query, params = unlist(prescription_query$params)))",
		"prescription_data[, ':='(",
		"  start_date = as.IDate(start_date),",
		"  stop_date = as.IDate(stop_date)",
		")]",
		"setkey(prescription_data, patid, start_date)",
		"",
		"# LTC data query",
		"ltc_query <- list(",
		paste0("  query = '", ltc_query$query, "',"),
		paste0("  params = list(", paste(sprintf("'%s'", unlist(ltc_query$params)), collapse = ", "), ")"),
		")",
		"ltc_data <- as.data.table(dbGetQuery(con, ltc_query$query, params = unlist(ltc_query$params)))",
		"ltc_data[, ':='(",
		"  eventdate = as.IDate(eventdate),",
		"  patid = bit64::as.integer64(patid)",
		")]",
		"setkey(ltc_data, patid, age_days)",
		"",
		"# Outcome data query",
		"outcome_query <- list(",
		paste0("  query = '", outcome_query$query, "',"),
		paste0("  params = list(", paste(sprintf("'%s'", unlist(outcome_query$params)), collapse = ", "), ")"),
		")",
		"outcome_data <- as.data.table(dbGetQuery(con, outcome_query$query, params = unlist(outcome_query$params)))",
		"outcome_data[, ':='(",
		"  eventdate = as.IDate(eventdate),",
		"  patid = bit64::as.integer64(patid)",
		")]",
		"setkey(outcome_data, patid, eventdate)",
		"",
		"# Close database connection",
		"dbDisconnect(con)",
		""
	)

	# Add data processing code
	processing <- c(
		"# Process data to create outcome_prescriptions",
		"message('Computing outcome prescriptions ', Sys.time())",
		"",
		"# Pre-filter prescription data for efficiency",
		"presc_df <- prescription_data[patid %in% outcome_data$patid]",
		"",
		"# Get relevant patient-dates",
		"potential_matches <- outcome_data[, .(patid, eventdate, age_days)]",
		"setkey(potential_matches, patid)",
		"",
		"# Main join for prescriptions around outcome",
		"diag_presc <- potential_matches[presc_df,",
		"  .(patid,",
		"    eventdate = x.eventdate,",
		"    outcome_age = age_days,",
		"    substance,",
		"    start_date,",
		"    stop_date,",
		"    duration),",
		"  on = .(patid, eventdate > start_date),",
		"  nomatch = 0]",
		"",
		"# Filter for prescriptions within 30 days of outcome",
		"diag_presc <- diag_presc[stop_date >= eventdate-30]",
		"",
		"# Keep only patients with multiple substances",
		"multi_substance <- diag_presc[, if(.N > 1 && uniqueN(substance) > 1) .SD, by = patid]",
		"",
		"# Early exit if no matching patients",
		"if (nrow(multi_substance) == 0) stop('No matching patients found')",
		"",
		"# Pre-filter LTC data",
		"ltcs <- ltc_data[patid %in% multi_substance$patid]",
		"",
		"# Join with LTC data and get counts",
		"nltcs <- ltcs[multi_substance,",
		"  .(patid, eventdate, outcome_age, age_days, term),",
		"  on = .(patid, age_days < outcome_age),",
		"  nomatch = 0][, .(n_ltc = uniqueN(term)), by = patid]",
		"",
		"# Final filtering for multimorbid patients",
		"setkey(nltcs, patid)",
		"outcome_prescriptions <- multi_substance[nltcs[n_ltc > 1]]",
		"",
		"# Create subst_pp_df",
		"# Read BNF lookup table",
		"bnf_lookup <- fread('new_bnf_lkp.csv')",
		"",
		"# Join with BNF lookup and calculate polypharmacy groups",
		"subst_pp_df <- merge(outcome_prescriptions,",
		"  bnf_lookup[, .(BNF_Presentation_Code, BNF_Chemical_Substance)],",
		"  by.x = 'substance',",
		"  by.y = 'BNF_Presentation_Code',",
		"  all.x = TRUE)",
		"setkey(subst_pp_df, patid)",
		"",
		"# Calculate pp_groups",
		"pp_df <- unique(outcome_prescriptions[, .(patid, pp = length(unique(substance)))])",
		"breaks <- c(2, 4, 6, 8, 11, max(pp_df$pp, na.rm = TRUE))",
		"pp_df[, pp_group := findInterval(pp, breaks, rightmost.closed = TRUE)]",
		"",
		"# Create labels for pp_groups",
		"labels <- sprintf('[%g-%g)', breaks[-length(breaks)], breaks[-1])",
		"labels[length(labels)] <- sub('\\\\)', ']', labels[length(labels)])",
		"",
		"pp_df[, pp_group := factor(labels[pp_group],",
		"  levels = labels,",
		"  ordered = TRUE)]",
		"setkey(pp_df, patid)",
		"",
		"# Join pp_groups with subst_pp_df",
		"subst_pp_df <- subst_pp_df[pp_df]",
		"",
		"message('Finished processing ', Sys.time())",
		"",
		"# Print summary statistics",
		"cat('\\nSummary:\\n')",
		"cat('Number of patients:', uniqueN(subst_pp_df$patid), '\\n')",
		"cat('Number of unique substances:', uniqueN(subst_pp_df$substance), '\\n')",
		"cat('Distribution of PP groups:\\n')",
		"print(table(pp_df$pp_group))"
	)

	# Combine all content
	content <- c(header, libraries, queries, processing)

	# Write to file
	writeLines(content, file_path)
}